import { MarkerType } from "@xyflow/react";

export const getRandomMAStartNode = () => {
    const startNode = Math.floor(Math.random() * 15) + 9;
    return startNode.toString();
};

export const getRandomMAEndNode = () => {
    let endNode = Math.floor(Math.random() * 13) + 25;
    return endNode.toString();
};

export const getMANodes = () => {
    const nodes = [
        {
            id: "0",
            type: "custom",
            position: {
                x: 0,
                y: 0,
            },
            data: {
                label: "North Adams",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "9",
            type: "custom",
            position: {
                x: -91,
                y: 168,
            },
            data: {
                label: "Pittsfield",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "10",
            type: "custom",
            position: {
                x: -165,
                y: 396,
            },
            data: {
                label: "Sheffield",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "11",
            type: "custom",
            position: {
                x: 167,
                y: 212,
            },
            data: {
                label: "Chesterfield",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "12",
            type: "custom",
            position: {
                x: 329,
                y: 396,
            },
            data: {
                label: "Springfield",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "13",
            type: "custom",
            position: {
                x: 355,
                y: 20,
            },
            data: {
                label: "Bernardston",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "14",
            type: "custom",
            position: {
                x: 373,
                y: 216,
            },
            data: {
                label: "Amherst",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "15",
            type: "custom",
            position: {
                x: 567,
                y: 66,
            },
            data: {
                label: "Athol",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "16",
            type: "custom",
            position: {
                x: 501,
                y: 368.5,
            },
            data: {
                label: "Palmer",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "17",
            type: "custom",
            position: {
                x: 643,
                y: 396.5,
            },
            data: {
                label: "Fiskdale",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "18",
            type: "custom",
            position: {
                x: 797,
                y: 434.5,
            },
            data: {
                label: "Webster",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "19",
            type: "custom",
            position: {
                x: 1015,
                y: 452.5,
            },
            data: {
                label: "Blackstone",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "20",
            type: "custom",
            position: {
                x: 847,
                y: 290.5,
            },
            data: {
                label: "Worcester",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "21",
            type: "custom",
            position: {
                x: 875,
                y: 98.5,
            },
            data: {
                label: "Leominster",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "22",
            type: "custom",
            position: {
                x: 1087,
                y: 274.5,
            },
            data: {
                label: "Framingham",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "23",
            type: "custom",
            position: {
                x: 1219,
                y: 328.5,
            },
            data: {
                label: "Westwood",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "24",
            type: "custom",
            position: {
                x: 1189,
                y: 82.5,
            },
            data: {
                label: "Billerica",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "26",
            type: "custom",
            position: {
                x: 1361,
                y: -87.5,
            },
            data: {
                label: "Merrimack",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "27",
            type: "custom",
            position: {
                x: 1395,
                y: 126.5,
            },
            data: {
                label: "South Peabody",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "28",
            type: "custom",
            position: {
                x: 1609,
                y: 30.5,
            },
            data: {
                label: "Rockport",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "29",
            type: "custom",
            position: {
                x: 1321,
                y: 232.5,
            },
            data: {
                label: "Boston",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "30",
            type: "custom",
            position: {
                x: 1361,
                y: 400.5,
            },
            data: {
                label: "Brockton",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "31",
            type: "custom",
            position: {
                x: 1539,
                y: 330.5,
            },
            data: {
                label: "Scituate",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "32",
            type: "custom",
            position: {
                x: 1413,
                y: 548.5,
            },
            data: {
                label: "Middleborough",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "33",
            type: "custom",
            position: {
                x: 1279,
                y: 594.5,
            },
            data: {
                label: "Dighton",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "34",
            type: "custom",
            position: {
                x: 1413,
                y: 712.5,
            },
            data: {
                label: "New Bedford",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "35",
            type: "custom",
            position: {
                x: 1671,
                y: 620.5,
            },
            data: {
                label: "Sagamore",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "36",
            type: "custom",
            position: {
                x: 1956.5,
                y: 686.5,
            },
            data: {
                label: "Harwich",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "37",
            type: "custom",
            position: {
                x: 1994.5,
                y: 508.5,
            },
            data: {
                label: "Wellfleet",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "38",
            type: "custom",
            position: {
                x: 1680.5,
                y: 886.5,
            },
            data: {
                label: "Edgartown",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
        {
            id: "39",
            type: "custom",
            position: {
                x: 1894.5,
                y: 408.5,
            },
            data: {
                label: "Provincetown",
                isStart: false,
                isEnd: false,
                visited: false,
                isWall: false,
                isPath: false,
            },
        },
    ];
    return nodes;
};

export const getMALinks = () => {
    const links = [
        {
            id: "xy-edge__0-9",
            source: "0",
            target: "9",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__9-10",
            source: "9",
            target: "10",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__10-11",
            source: "10",
            target: "11",
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__11-12",
            source: "11",
            target: "12",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "5",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "10",
            target: "12",
            id: "xy-edge__10-12",
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "9",
            target: "11",
            id: "xy-edge__9-11",
        },
        {
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "0",
            target: "11",
            id: "xy-edge__0-11",
        },
        {
            id: "xy-edge__11-13",
            source: "11",
            target: "13",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__13-14",
            source: "13",
            target: "14",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "14",
            target: "12",
            id: "xy-edge__14-12",
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "11",
            target: "14",
            id: "xy-edge__11-14",
        },
        {
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "0",
            target: "13",
            id: "xy-edge__0-13",
        },
        {
            id: "xy-edge__13-15",
            source: "13",
            target: "15",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "14",
            target: "15",
            id: "xy-edge__14-15",
        },
        {
            id: "xy-edge__14-16",
            source: "14",
            target: "16",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "5",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "16",
            target: "15",
            id: "xy-edge__16-15",
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "12",
            target: "16",
            id: "xy-edge__12-16",
        },
        {
            id: "xy-edge__16-17",
            source: "16",
            target: "17",
            type: "floating",
            animated: false,
            label: "1",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__17-18",
            source: "17",
            target: "18",
            type: "floating",
            animated: false,
            label: "1",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__18-19",
            source: "18",
            target: "19",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__18-20",
            source: "18",
            target: "20",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__20-21",
            source: "20",
            target: "21",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "15",
            target: "21",
            id: "xy-edge__15-21",
        },
        {
            type: "floating",
            animated: false,
            label: "5",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "15",
            target: "20",
            id: "xy-edge__15-20",
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "17",
            target: "20",
            id: "xy-edge__17-20",
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "20",
            target: "19",
            id: "xy-edge__20-19",
        },
        {
            id: "xy-edge__19-22",
            source: "19",
            target: "22",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__22-23",
            source: "22",
            target: "23",
            type: "floating",
            animated: false,
            label: "1",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "19",
            target: "23",
            id: "xy-edge__19-23",
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "20",
            target: "22",
            id: "xy-edge__20-22",
        },
        {
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "21",
            target: "22",
            id: "xy-edge__21-22",
        },
        {
            id: "xy-edge__21-24",
            source: "21",
            target: "24",
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__26-27",
            source: "26",
            target: "27",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__27-28",
            source: "27",
            target: "28",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "24",
            target: "26",
            id: "xy-edge__24-26",
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "26",
            target: "28",
            id: "xy-edge__26-28",
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "24",
            target: "27",
            id: "xy-edge__24-27",
        },
        {
            id: "xy-edge__27-29",
            source: "27",
            target: "29",
            type: "floating",
            animated: false,
            label: "1",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "1",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "23",
            target: "29",
            id: "xy-edge__23-29",
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "22",
            target: "24",
            id: "xy-edge__22-24",
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "24",
            target: "29",
            id: "xy-edge__24-29",
        },
        {
            id: "xy-edge__29-30",
            source: "29",
            target: "30",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__30-31",
            source: "30",
            target: "31",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__31-32",
            source: "31",
            target: "32",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__30-33",
            source: "30",
            target: "33",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "19",
            target: "33",
            id: "xy-edge__19-33",
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "23",
            target: "30",
            id: "xy-edge__23-30",
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "30",
            target: "32",
            id: "xy-edge__30-32",
        },
        {
            id: "xy-edge__32-34",
            source: "32",
            target: "34",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__34-35",
            source: "34",
            target: "35",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__35-36",
            source: "35",
            target: "36",
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__36-37",
            source: "36",
            target: "37",
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            type: "floating",
            animated: false,
            label: "1",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "33",
            target: "32",
            id: "xy-edge__33-32",
        },
        {
            type: "floating",
            animated: false,
            label: "2",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "33",
            target: "34",
            id: "xy-edge__33-34",
        },
        {
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
            source: "32",
            target: "35",
            id: "xy-edge__32-35",
        },
        {
            id: "xy-edge__35-38",
            source: "35",
            target: "38",
            type: "floating",
            animated: false,
            label: "3",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__31-35",
            source: "31",
            target: "35",
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__34-38",
            source: "34",
            target: "38",
            type: "floating",
            animated: false,
            label: "4",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
        {
            id: "xy-edge__37-39",
            source: "37",
            target: "39",
            type: "floating",
            animated: false,
            label: "1",
            markerEnd: { type: MarkerType.ArrowClosed },
            data: { isReversed: false },
        },
    ];
    return links;
};
